name: line_all
description: "A new Flutter project."

publish_to: "none"

version: 1.4.2+7

# NOTE: The Dart SDK constraint has been updated from ">=3.4.0 <4.0.0" to ">=3.9.0 <4.0.0".
# Please ensure all team members update their Flutter SDK to at least 3.9.0.
environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  dio: ^5.9.0
  firebase_analytics: ^12.0.3
  firebase_core: ^4.2.0
  firebase_crashlytics: ^5.0.3
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  flutter_keyboard_visibility: ^6.0.0
  flutter_riverpod: ^3.0.3
  flutter_screenutil: ^5.9.0
  freezed_annotation: ^3.1.0
  go_router: ^16.2.4
  image: ^4.5.4
  intl: ^0.20.2
  json_annotation: ^4.9.0
  lottie: ^3.3.2
  mailer: ^6.6.0
  path_provider: ^2.1.5
  pdf: ^3.11.3
  pdfrx: ^2.2.18
  pretty_dio_logger: ^1.4.0
  printing: ^5.14.2
  shared_preferences: ^2.5.3
  tutorial_coach_mark: ^1.3.1
  url_launcher: ^6.3.2
  uuid: ^4.5.2

dev_dependencies:
  build_runner: ^2.4.8
  flutter_gen_runner: ^5.4.0
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
  json_serializable: ^6.11.1

flutter:
  uses-material-design: true
  assets:
    - .env
    - lib/assets/icon/app_icon.png
    - lib/assets/fonts/NotoSansKR-Regular.ttf
    - lib/assets/destination_hierarchy.json
    - lib/assets/loading.json
    - lib/assets/lax_logo.png
    - lib/assets/lineall_logo.png
    - lib/assets/lineall_logo2.png
    - lib/assets/laxgp_logo.png
    - lib/assets/laxgp_logo2.png
    - lib/assets/optilo_logo.png
    - lib/assets/truck_image.png
    - lib/assets/laxgp_splash.png
    - lib/assets/lineall_splash.png

  fonts:
    - family: NoonnuFont
      fonts:
        - asset: lib/assets/fonts/ChangwonDangamRound.ttf

flutter_icons:
  android: true
  ios: false
  image_path: "lib/assets/icon/app_icon.png"
